# Generated by Django 4.0 on 2021-12-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tempdata_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdata',
            name='name',
        ),
        migrations.AlterField(
            model_name='tempdata',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
