# Generated by Django 4.0 on 2021-12-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_tempdata_name_alter_tempdata_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdata',
            name='temp',
        ),
        migrations.AddField(
            model_name='tempdata',
            name='temp_env',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='temp_obj',
            field=models.FloatField(null=True),
        ),
    ]
